// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACK-SzHjKt1tujtnhsbtfgT8YsciUFAis',
    appId: '1:791769530597:web:65f9287f72667d0817940c',
    messagingSenderId: '791769530597',
    projectId: 'skymain-c0827',
    authDomain: 'skymain-c0827.firebaseapp.com',
    storageBucket: 'skymain-c0827.firebasestorage.app',
    measurementId: 'G-B9GYBHHG89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFsbdQruBQB97kzh2Mpeb1NxStQFU8P4U',
    appId: '1:791769530597:android:f46d8e59d544446917940c',
    messagingSenderId: '791769530597',
    projectId: 'skymain-c0827',
    storageBucket: 'skymain-c0827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6o3gEH1ZKu8NsB2sbI4UYRjoCAcd3Vc',
    appId: '1:791769530597:ios:6ca73d97c2053dea17940c',
    messagingSenderId: '791769530597',
    projectId: 'skymain-c0827',
    storageBucket: 'skymain-c0827.firebasestorage.app',
    iosBundleId: 'com.example.skychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6o3gEH1ZKu8NsB2sbI4UYRjoCAcd3Vc',
    appId: '1:791769530597:ios:6ca73d97c2053dea17940c',
    messagingSenderId: '791769530597',
    projectId: 'skymain-c0827',
    storageBucket: 'skymain-c0827.firebasestorage.app',
    iosBundleId: 'com.example.skychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACK-SzHjKt1tujtnhsbtfgT8YsciUFAis',
    appId: '1:791769530597:web:fead52690c2a594017940c',
    messagingSenderId: '791769530597',
    projectId: 'skymain-c0827',
    authDomain: 'skymain-c0827.firebaseapp.com',
    storageBucket: 'skymain-c0827.firebasestorage.app',
    measurementId: 'G-Q16XL7G2BX',
  );
}
